import { mediaUrl } from "./mediaUrl";

export type ResponsiveVariant = {
  widths: number[];
};

/** Lossless WebP variants generated by scripts/generate-responsive-images.mjs */
export const RESPONSIVE_VARIANTS: Record<string, ResponsiveVariant> = {
  "media/filtration.png": { widths: [640, 1024] },
  "media/uv.png": { widths: [640, 1024] },
  "media/ozone.png": { widths: [640, 1024] },
  "media/osmos.png": { widths: [640, 1024] },
  "media/back.png": { widths: [768, 1376] },
  "media/black.png": { widths: [480, 704] },
  "media/0,5.png": { widths: [640, 1024] },
  "media/1.5l.png": { widths: [640, 1024] },
  "media/mountain-lake-hero.jpg": { widths: [828] },
};

export const normalizeMediaPath = (src: string): string | null => {
  const match = src.match(/media\/[^?#]+/);
  return match?.[0] ?? null;
};

const stripExtension = (mediaPath: string): string => mediaPath.replace(/\.[^.]+$/, "");

export const buildWebpSrcSet = (mediaPath: string, widths: number[]): string =>
  widths
    .map((width) => `${mediaUrl(`${stripExtension(mediaPath)}-${width}.webp`)} ${width}w`)
    .join(", ");

export const getWebpSrcSet = (src: string): string | null => {
  const mediaPath = normalizeMediaPath(src);
  if (!mediaPath) return null;
  const variant = RESPONSIVE_VARIANTS[mediaPath];
  if (!variant) return null;
  return buildWebpSrcSet(mediaPath, variant.widths);
};

/** Pick the smallest variant that covers the current viewport width. */
export const getOptimalMediaUrl = (mediaPath: string, viewportWidth = window.innerWidth): string => {
  if (mediaPath === "media/mountain-lake-hero.jpg" && viewportWidth > 828) {
    return mediaUrl(mediaPath);
  }

  const variant = RESPONSIVE_VARIANTS[mediaPath];
  if (!variant) return mediaUrl(mediaPath);

  const base = stripExtension(mediaPath);
  const sorted = [...variant.widths].sort((a, b) => a - b);
  const chosen = sorted.find((width) => width >= viewportWidth) ?? sorted[sorted.length - 1];
  return mediaUrl(`${base}-${chosen}.webp`);
};
